name: cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: release') }}"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/release.yml
    secrets:
      APP_CLIENT_ID: ${{ vars.OCTO_BUDDY_CLIENT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.OCTO_BUDDY_PRIVATE_KEY }}
