name: ci

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:

jobs:
  lint-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/lint-pr.yml

  lint-commits:
    if: github.event_name == 'push' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/lint-commits.yml

  release-dry-run:
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/release.yml
    with:
      dry_run: true

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/release.yml
