name: tf-apply

on:
  workflow_call:
    secrets:
      TF_CLOUD_ORGANIZATION:
        required: true
      TF_WORKSPACE:
        required: true
      TF_API_TOKEN:
        required: true
      TF_GITHUB_TOKEN:
        required: true

jobs:
  tf-apply:
    name: tf-apply
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.x"
      - run: terraform init
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}
      - run: terraform apply -auto-approve -no-color
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}
