name: tf-apply

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      variables:
        required: false
        type: string
        default: ""
    secrets:
      TF_CLOUD_ORGANIZATION:
        required: true
      TF_API_TOKEN:
        required: true
      TF_GITHUB_TOKEN:
        required: true

jobs:
  tf-apply:
    name: tf-apply
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - uses: dflook/terraform-apply@v3.1.0
        with:
          workspace: ${{ inputs.workspace }}
          auto_approve: true
          variables: ${{ inputs.variables }}
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}
