name: tf-plan

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
    secrets:
      TF_CLOUD_ORGANIZATION:
        required: true
      TF_API_TOKEN:
        required: true
      TF_GITHUB_TOKEN:
        required: true
      TF_VAR_octo_buddy_private_key:
        required: true

jobs:
  tf-plan:
    name: tf-plan
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v7
      - uses: dflook/terraform-plan@v3.1.0
        with:
          workspace: ${{ inputs.workspace }}
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}
          TF_VAR_octo_buddy_private_key: ${{ secrets.TF_VAR_octo_buddy_private_key }}
